### ISSUE TITLE
[Client] Add rsyslog into meta-comodoo

### ISSUE THREAD

**Issue by javiroman** [comodoo/meta-comodoo#11]
Add Rsyslog by default in yocto image for single point of metrics and logs outputs.

**Comment by javiroman** [comment]
Example of rsyslog configuration for metrics gathering from Collectd:

`/etc/rsyslog.d/
             `-- collectd-csv.conf
`

The files tracked by rsyslog (collectd created files):

`global(workDirectory="/var/lib/rsyslog")

module(load="imfile")
module(load="omprog")

#
# CPU collectd metrics
#
ruleset(name="cpu_system"){
        action(type="omprog" binary="/root/syslog2httpjson.py")
}
input(type="imfile"
      File="/var/lib/collectd/csv/producer-node1/cpu-0/cpu-system-*"
      Tag="TAG_metric_cpu_system"
      ruleset="cpu_system")


ruleset(name="cpu_idle"){
        action(type="omprog" binary="/root/syslog2httpjson.py")
}
input(type="imfile"
      File="/var/lib/collectd/csv/producer-node1/cpu-0/cpu-idle-*"
      Tag="TAG_metric_cpu_idle"
      ruleset="cpu_idle")

ruleset(name="cpu_interrupt"){
        action(type="omprog" binary="/root/syslog2httpjson.py")
}
input(type="imfile"
      File="/var/lib/collectd/csv/producer-node1/cpu-0/cpu-interrupt-*"
      Tag="TAG_metric_cpu_interrupt"
      ruleset="cpu_interrupt")


ruleset(name="cpu_cpunice"){
        action(type="omprog" binary="/root/syslog2httpjson.py")
}
input(type="imfile"
      File="/var/lib/collectd/csv/producer-node1/cpu-0/cpu-nice-*"
      Tag="TAG_metric_cpu_nice"
      ruleset="cpu_cpunice")


ruleset(name="cpu_softirq"){
        action(type="omprog" binary="/root/syslog2httpjson.py")
}
input(type="imfile"
      File="/var/lib/collectd/csv/producer-node1/cpu-0/cpu-softirq-*"
      Tag="TAG_metric_cpu_softirq"
      ruleset="cpu_softirq")

ruleset(name="cpu_steal"){
        action(type="omprog" binary="/root/syslog2httpjson.py")
}
input(type="imfile"
      File="/var/lib/collectd/csv/producer-node1/cpu-0/cpu-steal-*"
      Tag="TAG_metric_cpu_steal"
      ruleset="cpu_steal")


ruleset(name="cpu_user"){
        action(type="omprog" binary="/root/syslog2httpjson.py")
}
input(type="imfile"
      File="/var/lib/collectd/csv/producer-node1/cpu-0/cpu-user-*"
      Tag="TAG_metric_cpu_user"
      ruleset="cpu_user")


ruleset(name="cpu_wait"){
        action(type="omprog" binary="/root/syslog2httpjson.py")
}
input(type="imfile"
      File="/var/lib/collectd/csv/producer-node1/cpu-0/cpu-wait-*"
      Tag="TAG_metric_cpu_wait"
      ruleset="cpu_wait")
`

**Comment by javiroman** [comment]
We are using a external tool for extract the logs from the system: `syslog2httpjson.py`

This tool send the logs files in HTTP (layer 7) because of HAproxy router reception in remote server (used by OpenShift regular configurations).

**Comment by indisoluble** [comment]
@javiroman Where can I get `syslog2httpjson.py` ?

**Comment by javiroman** [comment]
Probably the best place is within the folder of rsyslog recipe.

**Comment by indisoluble** [comment]
Changes to complete this issue will be done in branch [krogoth-syslog](https://github.com/comodoo/meta-comodoo/tree/krogoth-syslog).

@javiroman Give me a sec to prepare a folder where you can upload your file.

**Comment by indisoluble** [comment]
@javiroman One more question, as far as I can tell, the idea is to add:

```
global(workDirectory="/var/lib/rsyslog")

module(load="imfile")
module(load="omprog")

#
# CPU collectd metrics
#
ruleset(name="cpu_system"){
        action(type="omprog" binary="/root/syslog2httpjson.py")
}
input(type="imfile"
      File="/var/lib/collectd/csv/producer-node1/cpu-0/cpu-system-*"
      Tag="TAG_metric_cpu_system"
      ruleset="cpu_system")


ruleset(name="cpu_idle"){
        action(type="omprog" binary="/root/syslog2httpjson.py")
}
input(type="imfile"
      File="/var/lib/collectd/csv/producer-node1/cpu-0/cpu-idle-*"
      Tag="TAG_metric_cpu_idle"
      ruleset="cpu_idle")

ruleset(name="cpu_interrupt"){
        action(type="omprog" binary="/root/syslog2httpjson.py")
}
input(type="imfile"
      File="/var/lib/collectd/csv/producer-node1/cpu-0/cpu-interrupt-*"
      Tag="TAG_metric_cpu_interrupt"
      ruleset="cpu_interrupt")


ruleset(name="cpu_cpunice"){
        action(type="omprog" binary="/root/syslog2httpjson.py")
}
input(type="imfile"
      File="/var/lib/collectd/csv/producer-node1/cpu-0/cpu-nice-*"
      Tag="TAG_metric_cpu_nice"
      ruleset="cpu_cpunice")

ruleset(name="cpu_softirq"){
        action(type="omprog" binary="/root/syslog2httpjson.py")
}
input(type="imfile"
      File="/var/lib/collectd/csv/producer-node1/cpu-0/cpu-softirq-*"
      Tag="TAG_metric_cpu_softirq"
      ruleset="cpu_softirq")

ruleset(name="cpu_steal"){
        action(type="omprog" binary="/root/syslog2httpjson.py")
}
input(type="imfile"
      File="/var/lib/collectd/csv/producer-node1/cpu-0/cpu-steal-*"
      Tag="TAG_metric_cpu_steal"
      ruleset="cpu_steal")


ruleset(name="cpu_user"){
        action(type="omprog" binary="/root/syslog2httpjson.py")
}
input(type="imfile"
      File="/var/lib/collectd/csv/producer-node1/cpu-0/cpu-user-*"
      Tag="TAG_metric_cpu_user"
      ruleset="cpu_user")


ruleset(name="cpu_wait"){
        action(type="omprog" binary="/root/syslog2httpjson.py")
}
input(type="imfile"
      File="/var/lib/collectd/csv/producer-node1/cpu-0/cpu-wait-*"
      Tag="TAG_metric_cpu_wait"
      ruleset="cpu_wait")
```

to the end of the default [rsyslog.conf](https://github.com/facebook/openbmc/blob/master/common/recipes-extended/rsyslog/files/rsyslog.conf).

**Am I right?**

**Comment by javiroman** [comment]
@indisoluble nope. The rsyslog.conf, the main file, load all the files with .conf in the rsyslog.d folder, so if we create the content of collectd (for example /etc/rsyslog.d/collectd-csv.conf) the file is automatically loaded by rsyslog main file.

**Comment by indisoluble** [comment]
@javiroman Whenever you can, please upload `syslog2httpjson.py` to folder [meta-comodoo/recipes-extended/rsyslog/rsyslog](https://github.com/comodoo/meta-comodoo/tree/krogoth-syslog/meta-comodoo/recipes-extended/rsyslog/rsyslog) (in branch `krogoth-syslog`).

**Comment by javiroman** [comment]
Done in 9a74557 https://github.com/comodoo/meta-comodoo/blob/krogoth-syslog/meta-comodoo/recipes-extended/rsyslog/rsyslog/syslog2httpjson.py

**Comment by indisoluble** [comment]
Finally, with the new `.bbappend` file added in commit 68e789d332adb41fe5a176097917c19a331d1b2e, we should be able to build _Yocto images_ with fully configured `collectd` & `rsyslog`.

Of course, more tests are required ... but so far so good.

**Comment by indisoluble** [comment]
On commit 8dd815c0001eb3eefcc868a7af258268f4d51f36, I removed `global(workDirectory="/var/lib/rsyslog")` from `collectd-csv.conf` because `rsyslog` thrown an error saying that the directory did not exist. Given that I could not see any reason to define this path, I decided to remove this line.

@javiroman What do you think?

**Comment by indisoluble** [comment]
On the other hand, I have found a couple of error while testing our _Yocto image_:
- The first time the RPi is booted, `rsyslog` does not send any data to the remote server. In the log, we can read that `rsyslog` is not able to find `/var/lib/collectd/cvs/comodoo-pos/cpu-0`. As I see it, `rsyslog` & `collectd` are launched at the same time but `rsyslog` tries to read this directory before the second creates it and it never tries again. To solve this situation, we can restart `rsyslog` or reboot the computer but none of these options _are_ satisfactory.
- Anyway, even if we manage to send the data retrieved by `collectd`, `rsyslog` stops sending it after a while ... the service is running and I can not find an error in the log ...

@javiroman Any comment about this? I am kind of lost at this point.

**Comment by indisoluble** [comment]
After rebasing `krogoth-syslog` with the last changes in `master`, `rsyslog` carries on sending data without problem ... however I do not see why.

Anyway, on the first boot, the RPi still fails on sending the data because of the reason explained above.

**Comment by indisoluble** [comment]
So, about the second point commented above, in the `rsyslog` log we can see as follows:

```
...
2017-03-12T21:07:40.879175+00:00 raspberrypi3 init: Id "S0" respawning too fast: disabled for 5 minut
2017-03-12T21:12:41.984461+00:00 raspberrypi3 init: Id "S0" respawning too fast: disabled for 5 minut
2017-03-12T21:17:42.353592+00:00 raspberrypi3 init: Id "S0" respawning too fast: disabled for 5 minut
2017-03-12T21:20:01.564180+00:00 raspberrypi3 connmand[284]: ntp: time slew -0.004784 s              
2017-03-12T21:22:43.721117+00:00 raspberrypi3 init: Id "S0" respawning too fast: disabled for 5 minut
2017-03-12T21:22:48.563939+00:00 raspberrypi3 rsyslogd: -- MARK --                                   
2017-03-12T21:23:38.304570+00:00 raspberrypi3 rsyslogd-2359: action 'action 17' resumed (module 'ompr
2017-03-12T21:23:48.286040+00:00 raspberrypi3 rsyslogd-2359: action 'action 22' resumed (module 'ompr
2017-03-12T21:23:48.301638+00:00 raspberrypi3 rsyslogd-2359: action 'action 16' resumed (module 'ompr
2017-03-12T21:23:48.302039+00:00 raspberrypi3 rsyslogd-2359: action 'action 23' resumed (module 'ompr
2017-03-12T21:23:48.302528+00:00 raspberrypi3 rsyslogd-2359: action 'action 19' resumed (module 'ompr
2017-03-12T21:23:48.303022+00:00 raspberrypi3 rsyslogd-2359: action 'action 18' resumed (module 'ompr
2017-03-12T21:23:48.303514+00:00 raspberrypi3 rsyslogd-2359: action 'action 20' resumed (module 'ompr
2017-03-12T21:23:48.304064+00:00 raspberrypi3 rsyslogd-2359: action 'action 21' resumed (module 'ompr
...
```

Once this point is reached, no more data is sent.

**Comment by javiroman** [comment]
Maybe we have to take a look to [Fluent-Bit](https://github.com/fluent/fluent-bit) [https://github.com/fluent/fluent-bit]. Fluentd Proyect are participants in Yocto Project [Fluentd Yocto Participant](https://www.yoctoproject.org/organization/fluentd-project).

**Comment by indisoluble** [comment]
Right, there is a recipe for Fluent-Bit [here](http://layers.openembedded.org/layerindex/recipe/50694/).

But before giving up collectd+rsyslog, I would like to know what is it failing. Most likely, it fails because I am doing something wrong, if I do not know what, I might repeat the same error later.

**Comment by indisoluble** [comment]
On `omprog` documentation we can read:

> Executes the configured program and feeds log messages to that binary via stdin. The binary is free to do whatever it wants with the supplied data. If the program terminates, it is re-started. If rsyslog terminates, the program’s stdin will see EOF. The program must then terminate. The message format passed to the program can, as usual, be modified by defining rsyslog templates.

Does `syslog2httpjson.py` die if there is no data to read? Although the message about `respawning ` should not be related to it.

Anyway, we are using [rsyslog v7.6.1](http://layers.openembedded.org/layerindex/recipe/48349/) which is quite old but that is the one available in [krogoth](https://www.yoctoproject.org/yoctoproject/krogoth). To use a newer one, we would have to update our layer to use [Morty](https://www.yoctoproject.org/yoctoproject/morty) which offers [rsyslog v8.22.0](http://layers.openembedded.org/layerindex/recipe/54532/) and also [Fluent-Bit](http://layers.openembedded.org/layerindex/recipe/54483/) which, by the way, it is not available in krogoth.

Maybe, we should work on issue #24 first and then come back to this one.

@javiroman what do you think?

**Comment by indisoluble** [comment]
As agreed, this issue is postponed until issue #24 is completed.

**Comment by indisoluble** [comment]
[krogoth-syslog](https://github.com/comodoo/meta-comodoo/tree/krogoth-syslog) will no longer be used, from this point on we will use [morty-fluentbit](https://github.com/comodoo/meta-comodoo/tree/morty-fluentbit).

**Comment by indisoluble** [comment]
For the record, the solution based on rsyslog+collectd has been discarded. Instead we are going to use fluent-bit.

However, the recipe for fluent-bit in meta-openembedded is too old and does not include the output plugin for HTTP.

So far, I have been able to prepare a recipe for fluentbit 0.8.0 (which includes the output plugin for HTTP). And I have also tried to deploy the version 0.10.0 but I get the following errors:

```
...
[2017/04/09 18:10:25] [error] [out_http] could not flush records (http_do=-1)
[2017/04/09 18:10:30] [error] [out_http] could not flush records (http_do=-1)
[2017/04/09 18:10:30] [error] [io] TCP connection failed: xxx.xxx.xxx.xxx:xx
[2017/04/09 18:10:30] [error] [out_http] no upstream connections available
[2017/04/09 18:10:30] [error] [io] TCP connection failed: xxx.xxx.xxx.xxx:xx
[2017/04/09 18:10:30] [error] [out_http] no upstream connections available
[2017/04/09 18:10:30] [error] [io] TCP connection failed: xxx.xxx.xxx.xxx:xx
[2017/04/09 18:10:30] [error] [out_http] no upstream connections available
[2017/04/09 18:10:31] [error] [out_http] could not flush records (http_do=-1)
...
```

I will try to prepare a recipe for fluent-bit 0.9.0 but after that, I will prepare the config. file for this service to be launched on booting up.

**Comment by indisoluble** [comment]
With fluent-bit 0.9.0 we get the same errors, so we will stick to version 0.8.0.

**Comment by indisoluble** [comment]
I am closing this issue now, however there are still a couple of steps to be done later on:
* Request URL of server where to send the info gathered by fluent-bit: Issue [comodoo-pos-wizard/#1](https://github.com/comodoo/comodoo-pos-wizard/issues/1) 
* Launch fluent-bit once the configuration is completed: Issue #31
